### ISSUE TITLE
Chrome extension loads chat form, not login address

### ISSUE THREAD

**Issue by TeHashX** [LiveHelperChat/livehelperchat-extensions#11]
After entering site address, shows "P" on extension and don't asking me for login but opens chat form page. Same thing if I enter manually login data in option.
Chrome v120.0.6099.110 (Official Build) (64-bit), LHC v4.29

![lhc2](https://github.com/LiveHelperChat/livehelperchat-extensions/assets/1405188/4c7f8524-96be-433b-a881-eac548937230)
![lhc1](https://github.com/LiveHelperChat/livehelperchat-extensions/assets/1405188/996e6156-3ddf-4dca-9a08-6dca5cb44f1b)

**Comment by remdex** [comment]
Please use dedicated browser if you want a standalone app E.g electron https://livehelperchat.com/demo-12c.html or just telegram integration :)

**Comment by TeHashX** [comment]
Something wrong with my install? Even with the electron app, shows start chat page, not login screen.

**Comment by remdex** [comment]
Back office can be found always at `https://demo.livehelperchat.com/site_admin/` `/site_admin/` or `index.php/site_admin/`

**Comment by TeHashX** [comment]
Instead of /lvhelp/index.php/lhc_web I put /lvhelp/lhc_web/index.php/site_admin and it works now in app but in chrome extension I get error

Refused to display 'https://mysite/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by remdex** [comment]
As I told. Try to use electon as chrome extension is not supported in general.

**Comment by TeHashX** [comment]
The reason I want to use chrome extension is for availability, worked fine in the past, but now if I'm not in chat tab, will make user offline.
I want to make department online between certain hours, and I disabled "Ignore users online statuses and use departments online hours" 
![user-lhc](https://github.com/LiveHelperChat/livehelperchat-extensions/assets/1405188/988c34f2-b902-4289-b5c8-9cbccd5a5acc)

but no matter if user is online or not, the widget still shows as online. The electron app is running minimized and after 30 minutes make user offline, instead with chrome extension was ok but now I can't get login page, just start chat page.

**Comment by remdex** [comment]
Setup online hours and force bot to follow online hours.
![image](https://github.com/LiveHelperChat/livehelperchat-extensions/assets/1146085/ab7d44bb-c0c9-401e-8a9c-0d9357673686)

**Comment by remdex** [comment]
Electron app should not force you make offline. Unless you have setup in your account 
![image](https://github.com/LiveHelperChat/livehelperchat-extensions/assets/1146085/3e95dce4-eee7-4f59-93a0-eacc4aa0ee81)
