### ISSUE TITLE
Where is the SSO extension? 

### ISSUE THREAD

**Issue by migue99angel** [LiveHelperChat/livehelperchat-extensions#6]
Hi, I was reading the Live Helper Chat documentation about the SSO and it references this repository. 

I see the singlesignon extension was removed from master, but it was there in this [commit](https://github.com/LiveHelperChat/livehelperchat-extensions/tree/ba6a5254bdc7e3714987e3776ebdc9d3e3e2f484).  

Could you explain me the reason ? I need it to integrate LHC in a third party systems

**Comment by remdex** [comment]
https://github.com/LiveHelperChat/sso-boilerplate
