### ISSUE TITLE
customstatus callback when chat is answered by an agent.

### ISSUE THREAD

**Issue by Mike-Benoit** [LiveHelperChat/livehelperchat-extensions#8]
For the customstatus callback, I know there is "new_chat.php" that is triggered when the chat is initiated by the end-user. 

But is there a customstatus callback that only triggers when the agent answers the chat?

**Comment by remdex** [comment]
Listen for `chat.accept` event.

Similar to this - https://github.com/LiveHelperChat/livehelperchat-extensions/blob/master/customstatus/bootstrap/bootstrap.php#L14

**Comment by Mike-Benoit** [comment]
How would that work with this customstatus callback, would creating a "chat_accept.php" file work for that? Or is there a better way to hook into these events?

**Comment by remdex** [comment]
Read few times what I wrote above... I gave a sample how to listen to that event...
