### ISSUE TITLE
Mattermost plugin still not loading

### ISSUE THREAD

**Issue by mizerek** [LiveHelperChat/livehelperchat-extensions#9]
debug results:

Warning: include_once(extension/mattermost/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/lhc.payfrit.com/extension/mattermost/classes/erlhcoreclassMattermostValidator.php on line 233

Warning: include_once(): Failed opening 'extension/mattermost/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/lhc.payfrit.com/extension/mattermost/classes/erlhcoreclassMattermostValidator.php on line 233

not sure what this autoload.php is, not found anywhere i looked nor in the zip

**Comment by remdex** [comment]
Did not followed manual and did not run composer command from extension dir...
